/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

import Conceptos.Servicio;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fuent
 */
public class VentanaServicios extends javax.swing.JDialog {

    //arraylist servicios
    private ArrayList<Servicio> listaServicios;
    
    /**
     * Creates new form VentanaServicios
     */
    public VentanaServicios(java.awt.Frame parent, boolean modal, ArrayList<Servicio> listaServicios) {
        super(parent, modal);
        initComponents();
        this.listaServicios = listaServicios;
        this.textFieldID.setEditable(false);
        this.textFieldID.setText(generarNuevoId());
        LlenarTabla(); 
    }

    private String generarNuevoId() {
        int maxId = 0;
        if (this.listaServicios != null) {
            for (Servicio s : this.listaServicios) {
                try {
                    int idNum = Integer.parseInt(s.getIdentificacion().trim());
                    if (idNum > maxId) {
                        maxId = idNum;
                    }
                } catch (NumberFormatException e) {
                    // ignorar
                }
            }
        }
        return String.valueOf(maxId == 0 ? 100 : maxId + 1);
    }

    
    private void LlenarTabla(){
        
        // Encabezados de las columnas de la tabla
        Vector <String> titulos = new Vector();
        titulos.addElement("ID");
        titulos.addElement("Nombre");
        titulos.addElement("Precios");
            
        // Estructura para almacenar las filas de datos
        Vector<Vector> filas = new Vector();
            
        // Poblado de filas con la información de cada persona
        for (Servicio s: this.listaServicios){
            Vector<String> fila = new Vector();
            fila.addElement(s.getIdentificacion());
            fila.addElement(s.getNombre());
            fila.addElement(s.getPrecio());
            filas.addElement(fila);
        }
            
        // Asignación del modelo de datos a la tabla
        DefaultTableModel modeloTabla = new DefaultTableModel(filas, titulos);
        this.tableServicios.setModel(modeloTabla);  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelServicios = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableServicios = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        labelID = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        textFieldID = new javax.swing.JTextField();
        textFieldNombre = new javax.swing.JTextField();
        textFieldPrecio = new javax.swing.JTextField();
        buttonLimpiar = new javax.swing.JButton();
        buttonNuevo = new javax.swing.JButton();
        buttonModificar = new javax.swing.JButton();
        buttonBorrar = new javax.swing.JButton();
        buttonSalir = new javax.swing.JButton();
        ButtonSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelServicios.setText("Servicios");

        tableServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio"
            }
        ));
        tableServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableServiciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableServicios);

        labelID.setText("ID:");

        labelNombre.setText("NOMBRE:");

        labelPrecio.setText("PRECIO:");

        textFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIDActionPerformed(evt);
            }
        });

        textFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPrecioActionPerformed(evt);
            }
        });

        buttonLimpiar.setText("Limpiar");
        buttonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLimpiarMouseClicked(evt);
            }
        });
        buttonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpiarActionPerformed(evt);
            }
        });

        buttonNuevo.setText("Nuevo");
        buttonNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNuevoMouseClicked(evt);
            }
        });
        buttonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNuevoActionPerformed(evt);
            }
        });

        buttonModificar.setText("Modificar");
        buttonModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonModificarMouseClicked(evt);
            }
        });
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });

        buttonBorrar.setText("Borrar");
        buttonBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBorrarMouseClicked(evt);
            }
        });

        buttonSalir.setText("Salir");
        buttonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSalirMouseClicked(evt);
            }
        });

        ButtonSalvar.setText("Salvar");
        ButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ButtonSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(buttonSalir))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(99, 99, 99)
                                    .addComponent(labelServicios))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addComponent(labelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addGap(24, 24, 24)
                                                        .addComponent(labelNombre))))
                                            .addGap(26, 26, 26))
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(buttonLimpiar)
                                            .addGap(23, 23, 23)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(buttonNuevo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                            .addComponent(buttonModificar)
                                            .addGap(30, 30, 30)
                                            .addComponent(buttonBorrar))
                                        .addComponent(textFieldID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                        .addComponent(textFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textFieldPrecio, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGap(0, 269, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelServicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(textFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecio)
                    .addComponent(textFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLimpiar)
                    .addComponent(buttonNuevo)
                    .addComponent(buttonModificar)
                    .addComponent(buttonBorrar))
                .addGap(83, 83, 83)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSalir)
                    .addComponent(ButtonSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIDActionPerformed

    private void buttonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLimpiarActionPerformed

    private void buttonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonNuevoActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void textFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPrecioActionPerformed

    private void tableServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableServiciosMouseClicked
        //obtener row
        int fila = tableServicios.getSelectedRow();
        
        //Actualizo los textfields
        if (fila != -1){
            textFieldID.setText(tableServicios.getValueAt(fila, 0).toString());
            textFieldNombre.setText(tableServicios.getValueAt(fila, 1).toString());
            textFieldPrecio.setText(tableServicios.getValueAt(fila, 2).toString());
        }
    }//GEN-LAST:event_tableServiciosMouseClicked

    private void buttonLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLimpiarMouseClicked
        //limpia los textfiel y la tabla
        textFieldID.setText(generarNuevoId());
        textFieldNombre.setText("");
        textFieldPrecio.setText("");
        tableServicios.clearSelection();
    }//GEN-LAST:event_buttonLimpiarMouseClicked

    private void buttonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSalirMouseClicked
        //Limpia y sale
        textFieldID.setText("");
        textFieldNombre.setText("");
        textFieldPrecio.setText("");
        tableServicios.clearSelection();
        this.dispose();
    }//GEN-LAST:event_buttonSalirMouseClicked

    private void buttonNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNuevoMouseClicked
        //obtener valores de la tabla
        String id = generarNuevoId();
        String nombre = textFieldNombre.getText().trim();
        String precio = textFieldPrecio.getText().trim();
        
        //validaciones
        if (nombre.isBlank() || precio.isBlank()){
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos deben estar completos");
            return;
        }
        
        for (Servicio s : listaServicios){
            if (s.getNombre().equalsIgnoreCase(nombre)){
                javax.swing.JOptionPane.showMessageDialog(this, "El servicio ya existe");
                return;
            }
        }
        
        //creacion nuevo servicio
        Servicio nuevoServicio = new Servicio();
        nuevoServicio.setIdentificacion(id);
        nuevoServicio.setNombre(nombre);
        nuevoServicio.setPrecio(precio);
        
        //añado el servicio y actualizo la tabla
        this.listaServicios.add(nuevoServicio);
        LlenarTabla();
        buttonLimpiarMouseClicked(null);
    }//GEN-LAST:event_buttonNuevoMouseClicked

    private void buttonModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonModificarMouseClicked
        int fila = tableServicios.getSelectedRow();
        
        //validaciones
        if (fila == -1){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un servicio para modificarlo");
                return;
        }
        
        //obtengo los valores 
        String id = tableServicios.getValueAt(fila, 0).toString();
        String nombre = textFieldNombre.getText().trim();
        String precio = textFieldPrecio.getText().trim();
        
        //validaciones
        if (nombre.isBlank() || precio.isBlank()){
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos deben estar completos");
            return;
        }
        
        //validar que no exista otro servicio con el mismo nombre
        for (Servicio s : listaServicios) {
            if (!s.getIdentificacion().equalsIgnoreCase(id) && s.getNombre().equalsIgnoreCase(nombre)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ya existe otro servicio con ese nombre");
                return;
            }
        }

        //encontrar servicio
        for (Servicio s : listaServicios){
            if (s.getIdentificacion().equalsIgnoreCase(id)){
                s.setNombre(nombre);
                s.setPrecio(precio);
                LlenarTabla();
                buttonLimpiarMouseClicked(null);
                return;
            }
        }
        javax.swing.JOptionPane.showMessageDialog(this, "Servicio no encontrado");
    }//GEN-LAST:event_buttonModificarMouseClicked

    private void buttonBorrarMouseClicked(java.awt.event.MouseEvent evt) {
        int fila = tableServicios.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un servicio para borrarlo");
            return;
        }
        
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de que desea eliminar el servicio seleccionado?",
            "Confirmar eliminación",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );
        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        String id = tableServicios.getValueAt(fila, 0).toString();
        for (int i = 0; i < listaServicios.size(); i++) {
            if (listaServicios.get(i).getIdentificacion().equalsIgnoreCase(id)) {
                listaServicios.remove(i);
                break;
            }
        }
        LlenarTabla();
        buttonLimpiarMouseClicked(null);
    }

    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {
        // Salvar a archivo XML (pendiente para cuando el compañero implemente el guardado)
        javax.swing.JOptionPane.showMessageDialog(this, "Guardado pendiente de implementar");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   VentanaServicios dialog = new VentanaServicios(new javax.swing.JFrame(), true);
               // dialog.addWindowListener(new java.awt.event.WindowAdapter() {
               //     @Override
               //     public void windowClosing(java.awt.event.WindowEvent e) {
               //         System.exit(0);
               //     }
               // });
              //  dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JButton buttonBorrar;
    private javax.swing.JButton buttonLimpiar;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JButton buttonNuevo;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelServicios;
    private javax.swing.JTable tableServicios;
    private javax.swing.JTextField textFieldID;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
